### ISSUE TITLE
Doom 3 [41560020]

### ISSUE THREAD

**Issue by kurayami6** [Cxbx-Reloaded/game-compatibility#358]
https://en.wikipedia.org/wiki/Doom_3
### Description

Game is not supported by HLE

### Dumps 

[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304117/Xbe.txt)

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1304118/KrnlDebug.txt)

### Status
**Previous behavior:**

**Current behavior:**

### Screenshots 

![capture](https://user-images.githubusercontent.com/31968468/30447512-b089b2a2-99cf-11e7-994d-67c682f70474.PNG)

**Comment by frankyfife** [comment]
### Description







```
![image](https://user-images.githubusercontent.com/16177808/39969067-1a31af10-56d7-11e8-9103-723c607003e0.png)

```

### Dumps 

no dump because all of my game dumps seems to be tampered, i have to redump of all my games :(
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1998645/Xbe.txt)

### Status
**Previous behavior:** 
none reported

**Current behavior:**

state-booting

### Screenshots <!-- Errors, Graphics, Glitches, ETC --

![image](https://user-images.githubusercontent.com/16177808/39969099-70c98370-56d7-11e8-9441-0b520efb0e25.png)
![image](https://user-images.githubusercontent.com/16177808/39969103-7906c2f0-56d7-11e8-9404-718643b9a5d4.png)

https://youtu.be/EhAxR_CUsik

**Comment by frankyfife** [comment]
![image](https://user-images.githubusercontent.com/16177808/40583976-4a879590-6199-11e8-9017-5ca7ad6a4616.png)

with Version 7292e78b

**Comment by CakeLancelot** [comment]
New Issue: #863
