### ISSUE TITLE
Sega GT 2002

### ISSUE THREAD

**Issue by SonicThePS4** [Cxbx-Reloaded/game-compatibility#776]
### Description
Uh-oh. :( 

```

```

### Dumps 
[xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2037337/xbe.info.txt)
[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/2037447/KrnlDebug.txt)

### Status
**Previous behavior:** 

**Current behavior:**

### Screenshots

![untitled](https://user-images.githubusercontent.com/39503785/40517032-57b74b9e-5f81-11e8-9570-bea017e70d9e.png)

**Comment by CakeLancelot** [comment]
Please verify that the game dumps you're using are unmodified (ex. no region free hacks or anti-piracy bypasses). The program you're using may add them automatically, the best way to do it would be to FTP the files directly from your Xbox.

Also, if this is from the JSRF/Sega GT 2002 combo disc it should be reported [here](https://github.com/Cxbx-Reloaded/game-compatibility/issues/714).

**Comment by SonicThePS4** [comment]
Oh okay. I sure will. But no is not. I got Jet Set Radio Future & Sega GT 2002 separately.

**Comment by LukeUsher** [comment]
Unfortunately we cannot provide support for downloaded titles. There are a few reasons for this.

1. The obvious legal side of things: If we are seen support piracy, the project could be at risk of legal action/takedown.
2. Most pirated Xbox games are bad rips: They have missing data, patched code, etc. Most of the time this doesn't cause any issues, but it can. We have no idea what patches have been applied.
3. Title identification: Because of the applied region patches in most pirated dumps, it is near-impossible to determine which version of the game is being used, so we have no idea if any reported issues are specific to a regional variant or not.

**Comment by SonicThePS4** [comment]
@LukeUsher Ah okay, Thank you so much for letting me know.

**Comment by HyperScorpio** [comment]
Now Boots 100% only crash debug choosing a car.
