### ISSUE TITLE
Star Wars Battlefront demo [?]

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Cxbx-Reloaded/game-compatibility#872]
### Description

```
No error is given, it does allow me to open it but it doesn’t play.
The XBE is from the Star Wars trilogy Special Edition DVD set bonus disc (2004)
```

### Status
**Previous behavior:** 

**Current behavior:** none reported

**Comment by LukeUsher** [comment]
Thanks for reporting.

Could you please attach an Xbe dump text file (Edit -> Dump XBE Info To -> File), so we can investigate further

**Comment by LukeUsher** [comment]
This should be fixed by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/1584
The game still won't run, but it doesn't crash the emulator anymore.

Please could you upload an Xbe dump as detailed in my previous comment, so we can fill in the remaining information about this issue, and make sure we were both testing with the same version.

**Comment by LukeUsher** [comment]
Interesting note: This appears to be the first title we have ran into that requires a specific dashboard version to even attempt to boot.

**Comment by Margen67** [comment]
Will reopen once Xbe dump and KrnlDebug.txt are provided.
