### ISSUE TITLE
Jet set radio future PAL No characters

### ISSUE THREAD

**Issue by blueguts** [Cxbx-Reloaded/game-compatibility#933]
Description
When I open the game jet set radio future version pal, the characters of the games do not appear, they are invisible.

Dumps
[Xbe.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/4015640/Xbe.txt)

Status
Previous behavior:
None reported

Current behavior:
The title screen is slow, and no characters from the game appear on the screen.

Screenshot
![Capture](https://user-images.githubusercontent.com/36505229/71663868-24bd1e80-2d57-11ea-9353-b06e09ee5007.PNG)

**Comment by blueguts** [comment]
worked in version 337a9f69 (July 15, 2019) but not anymore

**Comment by LukeUsher** [comment]
Please follow the normal format for posting game compatibility issues (There is already an entry for this game so any info should be posted on that location)..

That being said: Do you happen to have an AMD GPU by any chance?

Since we switched to HLSL vertex shaders,compatibility and accuracy has dramatically increased, however, some AMD users have noticed issues like this.

Please try a wrapper such as D9VK.

The AMD issue is being tracked here: https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1803

**Comment by blueguts** [comment]
> Veuillez suivre le format normal pour signaler les problèmes de compatibilité des jeux (il y a déjà une entrée pour ce jeu, donc toutes les informations doivent être publiées à cet endroit).
> 
> Cela étant dit: avez-vous par hasard un GPU AMD?
> 
> Depuis que nous sommes passés aux vertex shaders HLSL, la compatibilité et la précision ont considérablement augmenté, cependant, certains utilisateurs d'AMD ont remarqué des problèmes comme celui-ci.
> 
> Veuillez essayer un wrapper tel que D9VK.
> 
> Le problème AMD est suivi ici: [Cxbx-Reloaded / Cxbx-Reloaded # 1803](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1803)

Many thanks for your answer but I don't know how to use a wrapper. Do you have a link? thanks again
